import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts and .next are generated by Next; they aren't ours to lint.
    ignores: ["next-env.d.ts", ".next/**", "node_modules/**", "storage/**"],
  },
];

export default config;
